packages:
  - .
  - aws-cdk
  - databricks-external-location

allowBuilds:
  '@pulumi/std': false
  esbuild: false
  protobufjs: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - pnpm@11.20.0
  - brace-expansion@5.0.9

overrides:
  '@opentelemetry/core@<2.8.0': ^2.8.0
  brace-expansion@>=4.0.0 <5.0.9: ^5.0.9
  eslint-import-resolver-typescript: '^4.4.5'
  semver: '>=7'

trustPolicy: no-downgrade
