packages:
  - .
  - aws-cdk
  - databricks-external-location

allowBuilds:
  '@pulumi/std': false
  esbuild: false
  protobufjs: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - pnpm@11.5.3

overrides:
  eslint-import-resolver-typescript: '>=4'
  semver: '>=7'

trustPolicy: no-downgrade
